services:
  sshitmaids:
    build: ./container
    image: sshitmaids:latest
    container_name: sshitmaids
    environment:
      - SSHITMAIDS_DEST_HOST=${SSHITMAIDS_DEST_HOST:-"github.com"}
      - SSHITMAIDS_PORT=${SSHITMAIDS_PORT:-2222}
      - SSHITMAIDS_DEST_PORT=${SSHITMAIDS_DEST_PORT:-22}
    ports:
      - "${SSHITMAIDS_PORT:-2222}:22"
    volumes:
      - ./volumes/ssh/sshitmaids:/root/sshitmaids
      - ./volumes/ssh/client:/root/ssh-client
    restart: unless-stopped